title: realjame
email: james@realja.me
description: >- # this means to ignore newlines until "baseurl:"
  realjame is a personal website and blog that writes about a variety of topics: mainly tech such as web development and old Roblox games.
baseurl: ""
url: "https://realja.me"
twitter_username: real__jame
# github_username: real-jame

defaults:
  - scope:
      path: blog
      type: posts
    values:
      category: blog
      permalink: "/blog/:title.html"
  - scope:
      path: dailynote
      type: "posts"
    values:
      category: dailynote
      permalink: "/dailynote/:title.html"
  - scope:
      path: devlog
      type: posts
    values:
      category: devlog
      permalink: "/devlog/:title.html"
future: true

categories:
  - dailynote
  - blog
  - devlog
category_display_names:
  blog: Blog Posts
  dailynote: Daily Notes
  devlog: Devlogs
categoryicons:
  blog: "/assets/feedicons-color/01.png"
  dailynote: "/assets/feedicons-color/16.png"
  devlog: "/assets/feedicons-color/25.png"
  all: "/assets/silk/feed.png"

tagicons:
  news: "/assets/silk/newspaper.png"
  personal: "/assets/silk/user_comment.png"
  roblox: "/assets/silk/brick.png"
  web: "/assets/silk/world.png"
  travel: "/assets/silk/car.png"
  prototype: "/assets/silk/cog.png"
  note: "/assets/silk/note.png"
  textarea.site: "/assets/silk/page_white_edit.png"
  tech: "/assets/silk/computer.png"
  thought: "/assets/silk/heart.png"
  bookmark: "/assets/silk/tag_blue.png"
callouticons:
  note: "/assets/silk/note.png"
  info: "/assets/silk/information.png"
  summary: "/assets/silk/page.png"
  todo: "/assets/silk/note_edit.png"
  tip: "/assets/silk/lightbulb.png"
  success: "/assets/silk/tick.png"
  question: "/assets/silk/help.png"
  warning: "/assets/silk/error.png"
  failure: "/assets/silk/cross.png"
  danger: "/assets/silk/exclamation.png"
  bug: "/assets/silk/bug.png"
  example: "/assets/silk/magnifier.png"
  quote: "/assets/silk/book_open.png"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
  smart_quotes: [apos, apos, quot, quot]
  typographic_symbols: { hellip: ... }
feed:
  posts_limit: 9999
