version: "3.8"
services:
  jekyllbuild:
    build:
      context: -
      args:
        build-command: "bundle exec jekyll serve --watch --drafts --incremental --config _config-dev.yml"
    volumes:
      - "./jameblog:/srv/jekyll"
  nginx:
    image: nginx:latest
    container_name: realja.me
    volumes:
      - ./src:/usr/share/nginx/html
    ports:
      - 1000:80
      - 1001:443
    restart: unless-stopped