version: "3.8"
services:
  jekyll:
    image: jekyll/jekyll:latest
    environment:
      - JEKYLL_ENV=production
      - JEKYLL_UID=1000
      - JEKYLL_GID=1000
    command: jekyll serve --verbose
    container_name: realja.me
    ports:
      - 1000:4000
    volumes:
      - ./src:/srv/jekyll
    restart: unless-stopped
