title: realjame
email: james@realja.me
description: >- # this means to ignore newlines until "baseurl:"
  realjame is a personal website and blog that writes about a variety of topics: mainly tech such as web development and old Roblox games.
baseurl: "/"
url: "https://realja.me"
twitter_username: real__jame
# github_username: real-jame

defaults:
  - scope:
      path: "blog"
      type: "posts"
    values:
      category: blog
      permalink: /blog/:title.html
  - scope:
      path: "daily/_posts"
      type: "posts"
    values:
      section: daily
      permalink: /daily/:title.html
  - scope:
      path: "devlog/_posts"
      type: "posts"
    values:
      category: devlog
      permalink: /devlog/:title.html
future: true

tagicons:
  News: "/assets/silk/newspaper.png"
  Personal: "/assets/silk/user_comment.png"
  Roblox: "/assets/silk/brick.png"
  Web: "/assets/silk/world.png"
  Travel: "/assets/silk/world_go.png"



# Build settings
plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  smart_quotes: [apos, apos, quot, quot]
  typographic_symbols: { hellip: ... }
