title: realjame
email: james@realja.me
description: >- # this means to ignore newlines until "baseurl:"
  realjame is a personal website and blog that writes about a variety of topics: mainly tech such as web development and old Roblox games.
baseurl: "/"
url: "https://realja.me"
twitter_username: real__jame
# github_username: real-jame

defaults:
  - scope:
      path: "blog"
      type: "posts"
    values:
      section: blog
      permalink: /blog/:title.html
  - scope:
      path: "daily/_posts"
      type: "posts"
    values:
      section: daily
      permalink: /daily/:title.html
future: true

# Build settings
plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  smart_quotes: [apos, apos, quot, quot]
  typographic_symbols: { hellip: ... }
